package com.turkninja.petshop.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum AppMessage {

    // COMMON (CMN)
    // Status Code (400)
    BAD_CREDENTIALS(HttpStatus.BAD_REQUEST, "CMN_4000001"),
    RECORD_NOT_FOUND(HttpStatus.BAD_REQUEST, "CMN_4000002"),
    BAD_REQUEST(HttpStatus.BAD_REQUEST, "CMN_4000003"), //DB'de YOK
    JSON_OBJECT_NOT_VALID(HttpStatus.BAD_REQUEST, "CMN_4000004"), //DB'de YOK
    VALIDATION_BIND_EXCEPTION(HttpStatus.BAD_REQUEST, "CMN_4000005"), //DB'de YOK
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "CMN_4000006"), //DB'de YOK
    HTTP_MEDIA_TYPE_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, "CMN_4000007"), //DB'de YOK
    HTTP_MESSAGE_NOT_READABLE(HttpStatus.BAD_REQUEST, "CMN_4000008"), //DB'de YOK
    METHOD_ARGUMENT_NOT_VALID(HttpStatus.BAD_REQUEST, "CMN_4000009"), //DB'de YOK
    INVALID_FORMAT_EXCEPTION(HttpStatus.BAD_REQUEST, "CMN_4000010"), //DB'de YOK
    MISSING_ARGUMENT_EXCEPTION(HttpStatus.BAD_REQUEST, "CMN_4000011"), //DB'de YOK
    INCONSISTENT_DATA_EXCEPTION(HttpStatus.BAD_REQUEST, "CMN_4000012"), //DB'de YOK
    TOKEN_EXPIRED_ERROR(HttpStatus.BAD_REQUEST, "CMN_4000013"), //DB'de YOK
    INVALID_TOKEN_ERROR(HttpStatus.BAD_REQUEST, "CMN_4000014"), //DB'de YOK
    DUPLICATE_RECORD(HttpStatus.BAD_REQUEST, "CMN_4000015"), //DB'de YOK
    ALREADY_EXIST(HttpStatus.BAD_REQUEST, "CMN_4000016"), //DB'de YOK
    EXPIRED_OR_INVALID_SSO_TOKEN(HttpStatus.BAD_REQUEST, "CMN_4000017"),
    METHOD_ARGUMENT_NOT_VALID_ERROR(HttpStatus.BAD_REQUEST,"CMN_4000018"),
    // Status Code (401)
    UNSUPPORTED_SECURITY_COMBINATION(HttpStatus.UNAUTHORIZED, "CMN_4010001"),
    EXPIRED_OR_INVALID_JWT_TOKEN(HttpStatus.UNAUTHORIZED, "CMN_4010002"),
    AUTHORIZATION_ERROR(HttpStatus.UNAUTHORIZED, "CMN_4010003"),
    // Status Code (403)
    AUTHENTICATION_ERROR(HttpStatus.FORBIDDEN, "CMN_4030001"), //DB'de YOK
    ACCOUNT_ACTIVATION_ERROR(HttpStatus.FORBIDDEN, "CMN_4030002"), //DB'de YOK
    LOGIN_ATTEMPT_LIMIT_ERROR(HttpStatus.FORBIDDEN, "CMN_4030003"), //DB'de YOK
    RESET_PASSWORD_TOKEN_INVALID_ERROR(HttpStatus.FORBIDDEN, "CMN_4030004"), //DB'de YOK
    CURRENT_PASSWORD_NOT_MATCHED_ERROR(HttpStatus.FORBIDDEN, "CMN_4030005"), //DB'de YOK
    // Status Code (404)
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "CMN_4040001"),//DB'de YOK
    // Status Code (405)
    HTTP_REQUEST_METHOD_NOT_SUPPORTED(HttpStatus.METHOD_NOT_ALLOWED, "CMN_4050001"), //DB'de YOK
    // Status Code (500)
    INTERNAL_SYSTEM_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "CMN_5000001"),

    //APPLICATION (APP)
    // Status Code (500)
    APPLICATION_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "APP_5000001"),
    EXTERNAL_API_CALL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "APP_5000002"), //DB'de yok

    //JAVAX_VALIDATION (JVL)
    // Status Code (400)
    JAVAX_VALIDATION_NOT_VALID_FIELD(HttpStatus.BAD_REQUEST, "JVL_4000001"),

    //CATEGORY
    // Status Code (500)
    CATEGORY_ALREADY_HAVE_PRODUCTS(HttpStatus.INTERNAL_SERVER_ERROR, "CAT_5000001");

    private final HttpStatus statusCode;

    private final String code;

    AppMessage(HttpStatus statusCode, String code) {
        this.statusCode = statusCode;
        this.code = code;
    }

}
